### ISSUE TITLE
Possible logic issue.

### ISSUE THREAD

**Issue by Gabriel-T-Harris** [Megan-VanHumbeck/Risk#7]
https://github.com/Megan-VanHumbeck/Risk/blob/0ebc1eef2699596539cf705c7d0cff146109f27e/Risk/Risk/Deck.cpp#L56

trade[1].type not compared with trade[2].type.

**Comment by Megan-VanHumbeck** [comment]
Thanks! That last check must have went missing when I refactored it. It is fixed now
